package com.tgayle.todolistexample;


import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.TextView;

import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;
import androidx.lifecycle.MutableLiveData;

import java.util.ArrayList;
import java.util.List;

public class MainActivity extends AppCompatActivity {

    // Create a special object that holds a list of Strings that Android can observe and watch the
    // changes of.
    MutableLiveData<List<String>> todos = new MutableLiveData<>();

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // Give the todos an initial value with no items.
        todos.setValue(new ArrayList<>());

        // Get access to the views that are on the screen using the id we gave them.
        // R. is a special class generated by Android that includes all your resources.
        final EditText input = findViewById(R.id.inputTextBox);
        Button addTodoButton = findViewById(R.id.addTodoButton);
        LinearLayout todoContainer = findViewById(R.id.todoContainer);

        // Tell the activity to listen to changes to our todos.
        todos.observe(this, listOfTodos -> {
            // Prefer Log.d, Log.e, and Log.i instead of System.out.println on Android.
            Log.d("Todos", listOfTodos.toString());

            // Remove all the todos currently on the screen.
            todoContainer.removeAllViews();

            // Go through each string in the list and add it to the container we made.
            for (int i = 0; i < listOfTodos.size(); i++) {
                String todo = listOfTodos.get(i);

                // Create a TextView with a context. A 'context' contains special information about
                // the current activity such as themes, styles, colors, and information about the
                // system.
                TextView thisTodo = new TextView(this);
                thisTodo.setText(i + " " + todo);

                // Add the new TextView to the screen.
                todoContainer.addView(thisTodo);
            }
        });

        // Set a listener on the "Add" button that will be called whenever the button is pressed.
        addTodoButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                // Grab the current list of todos.
                List<String> currentTodos = todos.getValue();

                // Add the item the user just made to the list.
                currentTodos.add(input.getText().toString());

                // Use setValue here so Android knows to alert the activity that the list changed.
                todos.setValue(currentTodos);

                // Clear the input box where the user typed.
                input.setText("");
            }
        });
    }
}